Repository ethereum/execution-specs, pull requests merged in 2021-08, with the labels that each got.

#296 Update Mainnet Expected Date
  network-upgrades/mainnet-upgrades/london.md
Labels: A-doc

#297 Update to active JSON-RPC spec
  README.md
Labels: A-doc, C-enhance

#298 Mark dapptools as london ready
  network-upgrades/ecosystem-readiness.md
Labels: A-doc

#251 Require `gasPrice` field for both legacy and EIP-1559 transactions
  json-rpc/spec.json
Labels: A-rpc

#294 Add genesis block
  scripts/b2t.sh
  scripts/gen_genesis_config.go
  setup.cfg
  src/ethereum/assets/README.md
  src/ethereum/assets/mainnet.json
  src/ethereum/assets/mainnet_genesis_alloc_rlp.hex
  src/ethereum/frontier/vm/instructions/environment.py
  src/ethereum/genesis.py
  src/ethereum/utils.py
  tests/frontier/blockchain_st_test_helpers.py
  tests/frontier/helpers.py
  tests/frontier/test_rlp.py
  tests/frontier/test_trie.py
  tests/frontier/vm/vm_test_helpers.py
  tests/test_genesis.py
Labels: A-spec, C-enhance

#302 Add a proper state interface
  src/ethereum/frontier/eth_types.py
  src/ethereum/frontier/rlp.py
  src/ethereum/frontier/spec.py
  src/ethereum/frontier/state.py
  src/ethereum/frontier/trie.py
  src/ethereum/frontier/vm/__init__.py
  src/ethereum/frontier/vm/instructions/environment.py
  src/ethereum/frontier/vm/instructions/storage.py
  src/ethereum/frontier/vm/interpreter.py
  tests/frontier/blockchain_st_test_helpers.py
  tests/frontier/test_trie.py
  tests/frontier/vm/vm_test_helpers.py
  whitelist.txt
Labels: A-spec, C-enhance

#306 Move modules depending on frontier types into frontier hardfork
  src/ethereum/frontier/genesis.py
  src/ethereum/frontier/utils/hexadecimal.py
  src/ethereum/frontier/utils/json.py
  src/ethereum/utils/hexadecimal.py
  tests/frontier/blockchain_st_test_helpers.py
  tests/frontier/test_genesis.py
  tests/frontier/vm/vm_test_helpers.py
Labels: A-spec, C-bug
